 	select * from customers limit 5;
-- Q1. What is the total revenue generated by male vs. female customers?
	select gender,SUM(purchase_amount) as total_revenue
	from customers
	group by gender
	order by total_revenue desc;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
	-- Method 1
	select customer_id, purchase_amount 
	from customers
	where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customers );	
	-- Method 2
	select customer_id, purchase_amount, (select ROUND(avg(purchase_amount)) as avg_purchase_amount from customers )
	from customers
	where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customers );

-- Q3. Which are the top 5 products with the highest average review rating?
	select item_purchased,ROUND(avg(review_rating::numeric),2) as average_product_rating
	from customers
	group by item_purchased
	order by avg(review_rating) desc
	limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
	select shipping_type, round(avg(purchase_amount),2) as average_product_amount
	from customers
	where shipping_type in ('Standard','Express')
	group by shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
	select subscription_status,count(subscription_status),ROUND(avg(purchase_amount),2) as avg_spend ,sum(purchase_amount) as total_revenue
	from customers
	group by subscription_status
	order by avg_spend desc;
	
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
	select item_purchased,
	ROUND(100*sum(case when discount_applied='Yes' then 1 else 0 END)/count(*),2) as discount_rate
	from customers 
	group by item_purchased
	order by discount_rate desc
	limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
-- and show the count of each segment.
	WITH customer_type AS(
		select customer_id,previous_purchases,
		CASE WHEN previous_purchases=1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
			ELSE 'Loyal'
			END as cust_segment
		from customers	)
		
	SELECT cust_segment, count(*)
	FROM customer_type
	group by cust_segment;


-- Q8. What are the top 3 most purchased products within each category?
	with itemm_counts as (
		select category, item_purchased, count(customer_id) as total_orders,
		ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank
		from customers
		group by category,item_purchased
	)
	select item_rank,category,item_purchased,total_orders
	from itemm_counts 
	where item_rank<=3;
	
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
	SELECT subscription_status,
			count(customer_id)
	from customers
	WHERE previous_purchases>5
	GROUP BY subscription_status 
	
-- Q10. What is the revenue contribution of each age group?
	select age_group,
		sum(purchase_amount) as total_revenue
	from customers
	group by age_group 
	order by total_revenue desc;